name: Keep Supabase Alive - Project 1

on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Project
        run: |
          curl -f -L -I https://wealthforgeai.ashharnadeem.in/api/health
          curl -f -L -I https://cloudforgeai.ashharnadeem.in
          curl -f -L -I https://ashharnadeem.in
